name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: cur folder check
        run: ls -al
        
      - name: rm -rf folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf ~/lol-draft-simulator

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "~/lol-draft-simulator"
          strip_components: 1
          overwrite: true
          debug: true

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/lol-draft-simulator

            ls -al ~/lol-draft-simulator
            # 기존 컨테이너 중지 및 삭제 (있다면)
            docker stop lol-draft-simulator || true
            docker rm lol-draft-simulator || true
            
            # 최신 이미지 빌드 및 실행
            docker build -t lol-draft-simulator:latest .
            docker run -d -p 3000:3000 --restart=always --name lol-draft-simulator lol-draft-simulator:latest
            

